### ISSUE TITLE
Web Service API Down

### ISSUE THREAD

**Issue by tagsgreenhagen** [asharif/packit4me.com#13]
The API appears to be down by remote calls and samples on the site:
http://packit4me.com/api

Can you please check on this for us? Here are the error details:

---

HTTP Status 500 - 
type: Exception report
description: The server encountered an internal error () that prevented it from fulfilling this request.

exception: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.dao.DataAccessResourceFailureException: Hibernate flushing: could not insert: [com.packit4me.domain.RawApiCall]; SQL [insert into apicall (bins, callDate, items, userIp, call_type, id) values (?, ?, ?, ?, 'raw_call', ?)]; ERROR: could not access status of transaction 0
  Detail: Could not write to file "pg_subtrans/0097" at offset 49152: No space left on device.; nested exception is org.postgresql.util.PSQLException: ERROR: could not access status of transaction 0
  Detail: Could not write to file "pg_subtrans/0097" at offset 49152: No space left on device.
    org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:681)
    org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:585)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:641)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    org.sitemesh.webapp.contentfilter.ContentBufferingFilter.doFilter(ContentBufferingFilter.java:112)
    org.sitemesh.config.ConfigurableSiteMeshFilter.doFilter(ConfigurableSiteMeshFilter.java:163)
## note: The full stack trace of the root cause is available in the Apache Tomcat/7.0.26 logs.

Thanks in advance!

**Comment by asharif** [comment]
Should be back up.

**Comment by tagsgreenhagen** [comment]
Thank you so much! It's working again. Your quick response is much appreciated!
