### ISSUE TITLE
Unexpected Results for trivial problem

### ISSUE THREAD

**Issue by nabsul** [asharif/packit4me.com#23]
- Bin: 0:10:5x5x5
- Items: 3:0:5:1x1x1,2:0:5:1x1x1,9:0:5:1x1x1,4:0:5:1x1x1,5:0:5:1x1x1,6:0:5:1x1x1

Six boxes should fit easily in the 5x5x5 bin. When I tried out the graphical tool, it only packed 2 items in there.

**Comment by fuzknutz** [comment]
you give on 2nd parameter of bin as weight_limit for 10
so you can gain only for 2 items

**Comment by nabsul** [comment]
Doh! Sorry :-)
